name: Build & Publish

on:
  push:
    branches:
      - "main"
      - "!dependabot/**"

jobs:
  next-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - name: Upload Next build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .next
            public
          retention-days: 7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest